### PR TITLE
Create Hello world in lua

### PR DESCRIPTION
**Pull request by dibyaacharya**

### CODE REVIEW

**Comment by AselSiriwardena** [comment]
Please check the file naming convention from the [Readme](https://github.com/AselSiriwardena/hacktoberfest-beginner/blob/master/README.md)

**Comment by dibyaacharya** [comment]
Sir, I am not a good user accutally i am a noob I want to get the
hacktoberfest t shirt so I am doing this things please help me in this case
to get it in less time

**Comment by AselSiriwardena** [comment]
Don't worry we all are noobs.
All you want to is just rename the file as hello_world_ dibyaacharya.lua

**Comment by AselSiriwardena** [comment]
Copy past your code and add a new file (hello_world_ dibyaacharya.lua) and send the PR.
Simple as that. You don't need to know GIT at all.

**Comment by dibyaacharya** [comment]
> Copy past your code and add a new file (hello_world_ dibyaacharya.lua) in the [hello-world-2020](https://github.com/AselSiriwardena/hacktoberfest-beginner/tree/master/hello-world-2020) folder and send the PR.
> Simple as that. You don't need to know GIT at all.
To send pr I need to first and then 🤔

**Comment by AselSiriwardena** [comment]
Yeah.
I'm gonna close this PR, So it will easy for you.
You can start from the beginning.
All you need to do is change the file name, other than that everything fine

**Pull request closed without merging**
